### ISSUE TITLE
Clarification on resource some metric alarms and autoscaling policies

### ISSUE THREAD

**Issue by jorgeandresvasquez** [appzen-oss/terraform-aws-ecs-service-autoscale-step-sqs#1]
Hello folks from appzen-oss,

Let me start by thanking you for this awesome repo that has really helped me in understanding the options available to autoscale an ECS Fargate cluster using  StepScaling policies.

I have been trying to understand  few things that are not clear to me and help or a bit of clarification would be very appreciated:

1. What is being monitored with this expression:
`((visible + (taskcount * ${var.queue_task_worker_count})) * ${var.queue_worker_timing}) / (IF(taskcount==0, 1, taskcount) * ${var.queue_task_worker_count})`, what does queue_task_worker_count represent?

2.. What is the purpose of having the alarm:  "service_queue_big_high" in addition to "service_queue_high"?
3. Have you been successfully using this AutoScaling setup within your products and environments, is it meant to be pick and choose or having all policies is ideal?

Thanks in advance!

**Comment by wesleung** [comment]
1.  That expression is specific to our application.  Instead of only using SQS to determine when to scale.

- visible: SQS Visible messages
- taskcount: Number of currently running tasks
- queue_task_worker_count: Each task can process X SQS items.  In our case each of our tasks can handle 4 SQS messages at a time
- queue_worker_timing: Duration it takes to complete a SQS messages.

2. The big high is used for when there is a large jump in the number of jobs and you want to scale faster.  Let say you normally peak at 20k SQS and usually add 20 tasks between each cooldown.  But all of a sudden you have to process 100k SQS messages.  So the with the big scaling, you can set that to add 50 tasks between each cooldown when threshold of 40k SQS is passed.

3. You would normally choose either the service_queue (SQS only) or queue_up/down(expression), not both.

**Comment by jorgeandresvasquez** [comment]
Thanks a lot wesleung for clarifying, very appreciated!!
